#ifndef _ASM_X86_IRQ_VECTORS_H
#define _ASM_X86_IRQ_VECTORS_H

#define DIVIDE_ERROR_VECTOR		   0
#define DEBUG_VECTOR			   1
#define NMI_VECTOR			   2
#define BREAKPOINT_VECTOR		   3
#define OVERFLOW_VECTOR			   4
#define BOUNDS_CHECK_VECTOR		   5
#define INVALID_OPCODE_VECTOR		   6
#define DEVICE_NOT_AVAILABLE_VECTOR	   7
#define DOUBLE_FAULT_VECTOR		   8
#define COPROCESSOR_SEGMENT_OVERRUN_VECTOR 9
#define INVALID_TSS_VECTOR		   10
#define SEGMENT_NOT_PRESENT_VECTOR	   11
#define STACK_FAULT_VECTOR		   12
#define GENERAL_PROTECTION_FAULT_VECTOR	   13
#define PAGE_FAULT_VECTOR		   14
#define X87_FPU_VECTOR			   16
#define ALIGNMENT_CHECK_VECTOR		   17
#define MACHINE_CHECK_VECTOR		   18
#define SIMD_FP_VECTOR			   19
#define VIRTUALIZATION_VECTOR		   20

#define FIRST_EXTERNAL_VECTOR 32

#define PIC1_START_VECTOR 32
#define PIC2_START_VECTOR 40

#define NR_IRQS	   16
#define NR_VECTORS 256

#endif // _ASM_X86_IRQ_VECTORS_H